### ISSUE TITLE
ssSideNav.changeSectionVisible is not a function

### ISSUE THREAD

**Issue by d668** [sovanna/angular-material-sidenav#13]
following the [Usage](https://github.com/sovanna/angular-material-sidenav#3-usage) and have this error

**Comment by d668** [comment]
hey, is there any plans to fix this? thanks

**Comment by sovanna** [comment]
aa yes, i've forgotten.

changeSectionVisible is no longer existe.

use setVisible('ID', boolean) or setVisibleFor([ARRAY])
you can look an example on the demo app (home.js in controllers folder)

I'm gonna update the documentation asap, thanks.
