### ISSUE TITLE
Submenu not showing on sm devices

### ISSUE THREAD

**Issue by RenanGaleno** [sovanna/angular-material-sidenav#19]
On sm devices, the submenus are getting 0px height and not showing, when using updated dependencies versions

**Comment by RenanGaleno** [comment]
Debugging here, it's related with the fix for #17 on commit 8856a33ee9a84ffb38fa75be6ebb05849a6482da. The fix for this is undo that commit, but then the problem on #17 is still present. I'm trying to find another fix for that other issue.

**Comment by sovanna** [comment]
thx for helping!!

**Comment by RenanGaleno** [comment]
I discovered another problem related to this issue (when resizing from sm to md the submenu doesn't open anymore) that #21 was not fixing
