### ISSUE TITLE
Error: No instance found for handle left

### ISSUE THREAD

**Issue by bianca93** [sovanna/angular-material-sidenav#30]

**Comment by ipengyo** [comment]
![b94cb767-bce3-4959-8148-335ee8239a81](https://cloud.githubusercontent.com/assets/9323722/15476610/8c07a800-2142-11e6-931a-4b620b2353b4.png)

**Comment by ipengyo** [comment]
@sovanna  seek  help!!!!

**Comment by Quixomatic** [comment]
You don't have a sidenav with the md-component-id="left"

**Comment by Quixomatic** [comment]
@sovanna has extremely limited the use of their code to just a sidebar and has to be open to function. 

Removing:

```
                        if (!$mdMedia('gt-sm') && !$mdSidenav('left').isOpen() && open) {
                            return;
                        }
```

Will allow the sidenav to work in more than just a sidebar.
