### ISSUE TITLE
error while setting 'ssSideNav' factory to a controller

### ISSUE THREAD

**Issue by cerokool32** [sovanna/angular-material-sidenav#33]
I'm having troubles with this factory on the controller, but i can't find the reason.

https://docs.angularjs.org/error/$injector/unpr?p0=$stateProvider%20%3C-%20$state%20%3C-%20ssSideNav

**Comment by vontell** [comment]
Also having the same issue

**Comment by vontell** [comment]
I think I have found the issue: make sure that you have "ui.router" added to your module dependencies. @cerokool32  check that this works and close the issue if so

**Comment by cerokool32** [comment]
the error was an outdated version of ui.router. problem solved
