### ISSUE TITLE
angular-material version

### ISSUE THREAD

**Issue by ferater** [sovanna/angular-material-sidenav#7]
Hi Sovanna,
im using angular-material "~0.10.1", and angularjs "~1.4",
and getting : Error: [$injector:unpr] Unknown provider: ssSideNavSectionsProvider
can you adapt this?
sorry for my poor english.

**Comment by sovanna** [comment]
Hi, don't worry for your "english", I'm a french guy..so.. everyone can make mistakes ;)
Did you get this error also on the demo app ?

**Comment by ferater** [comment]
no, demo app working perfect

**Comment by sovanna** [comment]
did you include 'sasrio.angular-material-sidenav' as dep in your module app ?
did you add 'ssSideNavSectionsProvider' as dep in config function of your module app ?

**Comment by ferater** [comment]
i am solved this problem thank you

**Comment by sovanna** [comment]
oki
